blog/urls.py
from django.conf.urls import url
from .views import *



urlpatterns = [
    url(r'^$', blog_list, name="blog_list"),
    url(r'^blog_add/', blog_add, name="blog_add"),
    url(r'^blog_comment/', blog_comment, name="blog_comment"),

    url(r'^(?P<slug>[\w-]+)/$', blog_details, name="blog_details"),
    # url(r'^(?P<slug>[\w-]+)/blog_comment/', blog_comment, name="blog_comment"),
]

sample_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # path('myadmin/', admin.site.urls),
    url('admin/', admin.site.urls),
    url(r'^blog/', include(('blog.urls', 'blog'), namespace='blog')),
]

blog/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.core.urlresolvers import reverse


class Blog(models.Model):
    subject = models.CharField(max_length=1000, unique=True)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now=True)
    last_updated = models.DateTimeField(auto_now_add=True)
    content = models.TextField(max_length=10000)
    author = models.CharField(max_length=1000)

    def __str__(self):
        return self.subject

    def get_absolute_url(self):
        return reverse("blog:blog_details", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-last_updated"]


def create_slug(instance, new_slug=None):
    slug = slugify(instance.subject)

    if new_slug is not None:
        slug = new_slug
    qs = Blog.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()

    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

    # signal receiver
def pre_save_blog_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_blog_receiver, sender=Blog)


class Comment(models.Model):
    blog = models.ForeignKey(Blog)
    comment = models.CharField(max_length=1000)
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment

blog/forms.py
from django import forms
from .models import *


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = [
            'subject',
            'author',
            'content',
        ]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'comment',
        ]

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from .forms import *


def blog_list(request):
    blog = Blog.objects.all()
    context = {
        'blog': blog,
    }
    return render(request, 'blog/blog_list.html', context)


def blog_add(request):
    if request.method == 'POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            f = form.save()
            f.save()
            # return redirect('blog:blog_list')
            return HttpResponseRedirect(f.get_absolute_url())
    else:
        form = BlogForm()
    context = {
        'form': form,
    }
    return render(request, 'blog/blog_add.html', context)


def blog_details(request, slug):
    instance = get_object_or_404(Blog, slug=slug)
    comment = Comment.objects.all()
    context = {
        'instance': instance,
        'comment': comment,
    }
    return render(request, 'blog/blog_details.html', context)


def blog_comment(request):
    # instance = get_object_or_404(Blog, slug=slug)
    blog_id = request.POST["take_id"]
    blog_obj = Blog.objects.get(id=blog_id)  # for grabbing particular post's comments
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.blog = blog_obj
            f.save()
            print("hi")
            # return redirect('blog:blog_list')
            return HttpResponseRedirect(blog_obj.get_absolute_url())
    else:
        form = CommentForm()
    context = {
        'form': form,
    }
    return render(request, 'blog/blog_details', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

{% block content %}
{% endblock %}

</body></html>

templates/blog/blog_add.html
{% extends 'base.html' %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {% for field in form %}
        {{ field.label_tag }}
        {{ field }}<br/>
        {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}

        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
    {% endfor %}
    <button type="submit" class="btn btn-success">Add</button>
</form>

{% endblock %}

templates/blog/blog_details.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <h1 align="center">
        <b>
            {{instance.subject}}
        </b>
    </h1>
    <br/>
    <b>Author</b>: {{instance.author}}<br/><br/>
    <b>Date</b>: {{instance.last_updated}}<br/><br/>
    <b>Last Updated</b>: {{instance.timestamp}}<br/><br/>
    {{instance.content}}
    <hr/>

    <form method="post" action="{% url 'blog:blog_comment' %}">
        {% csrf_token %}
        <input type="hidden" name="take_id" value="{{ instance.id }}">
        <input type="text" placeholder="Comment" name="comment">
        <input type="submit" />
    </form>
    <br />
    {% for com in comment %}
        {% if com.blog.subject == instance.subject %}
            {{com}}<br/>
        {% endif %}
    {% endfor %}
</div>


{% endblock %}

templates/blog/blog_list.html
{% extends 'base.html' %}
{% block content %}
<br/>

<div class="container" style="">
    <div align="right">
        <a href="{% url 'blog:blog_add' %}" class="btn btn-success">Add Blog</a>
    </div>

    {% for b in blog %}
        <a href="{{b.get_absolute_url}}" class="btn btn-default">{{b}}</a>
        <hr/>
    {% endfor %}
</div>

{% endblock %}